# In file: alicia_duo_moveit/config/moveit_controllers.yaml

# All parameters for the simple controller manager and its controllers go under this namespace
moveit_simple_controller_manager:
  
  # List of controllers that the manager should be aware of
  controller_names:
    - alicia_controller

  alicia_controller:
    type: FollowJointTrajectory
    # The action_ns should be the same as the one provided by your ros2_control controller
    action_ns: follow_joint_trajectory 
    default: true
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6