# This file configures the OMPL planning pipeline.
move_group:
  # 1. Specify the default planning pipeline
  default_planning_pipeline: ompl

  # 2. Configure the OMPL pipeline itself
  ompl:
    # The planning plugin for OMPL
    planning_plugin: ompl_interface/OMPLPlanner

    # Planning request adapters - a space-separated string
    request_adapters: "default_planning_request_adapters/ResolveConstraintFrames default_planning_request_adapters/ValidateWorkspaceBounds default_planning_request_adapters/CheckStartStateBounds default_planning_request_adapters/CheckStartStateCollision"

    # Planning response adapters - a space-separated string
    response_adapters: "default_planning_response_adapters/AddTimeOptimalParameterization default_planning_response_adapters/ValidateSolution"

    # The library of all available planner configurations
    planner_configs:
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
      RRTstarkConfigDefault:
        type: geometric::RRTstar
        range: 0.0
        goal_bias: 0.05
        delay_collision_checking: 1

    arm:
      default_planner_config: RRTstarkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
      projection_evaluator: joints(joint1,joint6)
      longest_valid_segment_fraction: 0.05

    hand:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault
      projection_evaluator: joints(right_finger)
      longest_valid_segment_fraction: 0.05