planning_plugin: ompl_interface/OMPLPlanner

ompl:
  planning_time: 5.0 # seconds
  simplify_solutions: true

  # The planning group configurations
  # This must match the group name in your SRDF file
  alicia:
    # A list of available OMPL planners to use for this group
    planners:
      - RRTConnectkConfigDefault
      - PRMstarkConfigDefault
      - ESTkConfigDefault
      - LBKPIECEkConfigDefault
      - BKPIECEkConfigDefault
      - KPIECEkConfigDefault

    # Default planner for this group
    default_planner: RRTConnectkConfigDefault